#!/usr/bin/env python3
"""Dump live letter / emoji-So ranges for the browser engine."""

from __future__ import annotations

import unicodedata
from pathlib import Path


PREFIXES = (
    "LATIN ",
    "GREEK ",
    "CYRILLIC ",
    "CJK UNIFIED IDEOGRAPH",
    "CJK COMPATIBILITY IDEOGRAPH",
    "HIRAGANA ",
    "KATAKANA ",
    "KATAKANA-HIRAGANA ",
    "HANGUL SYLLABLE ",
    "BOPOMOFO ",
)


def assigned_name(character: str) -> str:
    try:
        return unicodedata.name(character)
    except ValueError:
        return ""


def is_live_letter(code: int) -> bool:
    character = chr(code)
    if not character.isalpha():
        return False
    if character.isascii():
        return True
    name = assigned_name(character)
    return any(name.startswith(prefix) for prefix in PREFIXES)


def is_emoji_so(code: int) -> bool:
    if not (0x2600 <= code <= 0x27BF):
        return False
    character = chr(code)
    return unicodedata.category(character) == "So"


def to_ranges(codes: list[int]) -> list[tuple[int, int]]:
    if not codes:
        return []
    ranges: list[tuple[int, int]] = []
    start = prev = codes[0]
    for code in codes[1:]:
        if code == prev + 1:
            prev = code
            continue
        ranges.append((start, prev))
        start = prev = code
    ranges.append((start, prev))
    return ranges


def emit_ts(name: str, ranges: list[tuple[int, int]]) -> str:
    lines = [
        "/* Generated by web/scripts/gen_unicode.py. Do not edit. */",
        f"export const {name}: ReadonlyArray<readonly [number, number]> = [",
    ]
    for start, end in ranges:
        lines.append(f"  [0x{start:04X}, 0x{end:04X}],")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    destination = Path(__file__).resolve().parents[1] / "src" / "engine" / "generated"
    destination.mkdir(parents=True, exist_ok=True)
    letters: list[int] = []
    emoji_so: list[int] = []
    for code in range(0x110000):
        if 0xD800 <= code <= 0xDFFF:
            continue
        if is_live_letter(code):
            letters.append(code)
        if is_emoji_so(code):
            emoji_so.append(code)
    letter_ranges = to_ranges(letters)
    emoji_ranges = to_ranges(emoji_so)
    (destination / "letters.ts").write_text(emit_ts("LIVE_LETTER_RANGES", letter_ranges), encoding="utf-8")
    (destination / "emoji-so.ts").write_text(emit_ts("EMOJI_SO_RANGES", emoji_ranges), encoding="utf-8")
    print(f"letters={len(letters)} ranges={len(letter_ranges)}")
    print(f"emoji_so={len(emoji_so)} ranges={len(emoji_ranges)}")


if __name__ == "__main__":
    main()
