__project_name__ = "FuckMark"
__version__ = "0.1.0"

from .adapters import (
    DEEPMIND_REFERENCE_ADAPTER_ID,
    DEEPMIND_REFERENCE_ALGORITHM_VERSION,
    DEEPMIND_REFERENCE_SOURCE_PIN,
    AdapterRegistry,
    AdapterSignals,
    DeepMindReferenceAdapter,
    DeepMindReferenceConfig,
    HUGGINGFACE_SYNTHID_ADAPTER_ID,
    HUGGINGFACE_SYNTHID_ALGORITHM_VERSION,
    HUGGINGFACE_SYNTHID_SOURCE_PIN,
    HuggingFaceSynthIDAdapter,
    HuggingFaceSynthIDConfig,
    WatermarkAdapter,
    create_deepmind_reference_adapter,
    create_huggingface_synthid_adapter,
    default_adapter_registry,
)
from .alignment import AlignmentOp, AlignmentResult, AlignmentStep, align_tokens, conserved_runs, validate_alignment
from .config import canonical_json_bytes, canonical_json_text, canonicalize
from .coverage import Interval, merge_intervals, substitution_observation_interval, union_size
from .hashing import derive_seed, sha256_bytes, sha256_file, sha256_json, sha256_text
from .detectors import (
    CompatibilityStatus,
    DetectorCompatibility,
    DetectorCompatibilityError,
    DetectorFamily,
    MEAN_ALGORITHM_VERSION,
    ScoreDirection,
    UncalibratedDetectorEvidence,
    WEIGHTED_MEAN_ALGORITHM_VERSION,
    ZeroValidObservationsError,
    evaluate_detector_compatibility,
    mean_evidence,
    mean_score,
    require_supported_detector,
    weighted_mean_evidence,
    weighted_mean_score,
)
from .native_observations import NativeObservationBatch, NativeObservationRecord, build_native_observations
from .observations import (
    StructuralObservationDiff,
    StructuralObservationState,
    StructuralObservationSummary,
    TokenNgram,
    build_token_ngrams,
    structural_observation_diff,
    summarize_structural_observations,
)
from .source_registry import SourcePinRegistry, load_source_pin
from .types import RunIdentity, SourcePin

__all__ = [
    "__project_name__",
    "__version__",
    "AdapterRegistry",
    "AdapterSignals",
    "AlignmentOp",
    "AlignmentResult",
    "AlignmentStep",
    "CompatibilityStatus",
    "DEEPMIND_REFERENCE_ADAPTER_ID",
    "DEEPMIND_REFERENCE_ALGORITHM_VERSION",
    "DEEPMIND_REFERENCE_SOURCE_PIN",
    "DetectorCompatibility",
    "DetectorCompatibilityError",
    "DetectorFamily",
    "DeepMindReferenceAdapter",
    "DeepMindReferenceConfig",
    "HUGGINGFACE_SYNTHID_ADAPTER_ID",
    "HUGGINGFACE_SYNTHID_ALGORITHM_VERSION",
    "HUGGINGFACE_SYNTHID_SOURCE_PIN",
    "HuggingFaceSynthIDAdapter",
    "HuggingFaceSynthIDConfig",
    "Interval",
    "MEAN_ALGORITHM_VERSION",
    "NativeObservationBatch",
    "NativeObservationRecord",
    "RunIdentity",
    "ScoreDirection",
    "SourcePin",
    "SourcePinRegistry",
    "StructuralObservationDiff",
    "StructuralObservationState",
    "StructuralObservationSummary",
    "TokenNgram",
    "UncalibratedDetectorEvidence",
    "WEIGHTED_MEAN_ALGORITHM_VERSION",
    "WatermarkAdapter",
    "ZeroValidObservationsError",
    "align_tokens",
    "build_native_observations",
    "build_token_ngrams",
    "canonical_json_bytes",
    "canonical_json_text",
    "canonicalize",
    "conserved_runs",
    "create_deepmind_reference_adapter",
    "create_huggingface_synthid_adapter",
    "default_adapter_registry",
    "derive_seed",
    "evaluate_detector_compatibility",
    "load_source_pin",
    "mean_evidence",
    "mean_score",
    "merge_intervals",
    "require_supported_detector",
    "sha256_bytes",
    "sha256_file",
    "sha256_json",
    "sha256_text",
    "structural_observation_diff",
    "substitution_observation_interval",
    "summarize_structural_observations",
    "union_size",
    "validate_alignment",
    "weighted_mean_evidence",
    "weighted_mean_score",
]
